name: jupyter-rtc
channels:
  - conda-forge
  - defaults
dependencies:
  - hypothesis
#  - jupyterlab=3.0.4
  - jupyter-packaging
  - jupyter-server-proxy
  - nbformat
  - nodejs=14.15.1
  - pycurl
  - pytest
  - python=3.9
  - rust
  - setuptools-rust
  - twine
  - yarn=1.22.5
  - pip:
    - jupyterlab-lsp
    - python-language-server[all]
